name: CI

on: [push]

jobs:
  build-cp35-cp35m:
    name: Python Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pyversion: ["cp35-cp35m", "cp36-cp36m", "cp37-cp37m", "cp38-cp38"]
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Build the Linux wheels
      run: |
        sudo docker run --rm -e PLAT=manylinux2014_x86_64 -v `pwd`:/io quay.io/pypa/manylinux2014_x86_64 /io/build-wheels.sh ${{ matrix.pyversion }}
    - name: Archive wheels
      uses: actions/upload-artifact@v1
      with:
        name: wheels
        path: wheelhouse