name: CI

on: [push]

jobs:
  build:
    name: Build the Wheels
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Build the Linux wheels
      run: |
        ./build-wheels.sh
