name: Pybind11 CI

on:
  push:
    branches:
      - master
      - cayley
  repository_dispatch:
    types: [pybind-wrapper]

jobs:
  build-new:
    name: New Wrapper Linux Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pyversion: ["cp35-cp35m", "cp36-cp36m", "cp37-cp37m", "cp38-cp38"]
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Build the Linux wheels
      run: |
        sudo docker run --rm -e PLAT=manylinux2014_x86_64 -v `pwd`:/io quay.io/pypa/manylinux2014_x86_64 /io/build-wheels-new.sh ${{ matrix.pyversion }}
    - name: Archive wheels
      uses: actions/upload-artifact@v1
      with:
        name: gtsam-4.0.3-${{ matrix.pyversion }}-manylinux2014_x86_64.whl
        path: wheelhouse/gtsam-4.0.3-${{ matrix.pyversion }}-manylinux2014_x86_64.whl
  new-mac-build:
    name: New Wrapper macOS Build
    runs-on: macos-latest
    strategy:
      matrix:
        pyversion: ["python"]
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Build the macOS wheels
      run: |
        ./build-macos-new.sh ${{ matrix.pyversion }}
    - name: Archive wheels
      uses: actions/upload-artifact@v1
      with:
        name: wheels
        path: ./wheelhouse