name: CI

on: [push]

jobs:
  build:
    name: Linux Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pyversion: ["cp27-cp27mu", "cp35-cp35m", "cp36-cp36m", "cp37-cp37m", "cp38-cp38"]
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Build the Linux wheels
      run: |
        if [[ "${{ matrix.pyversion }}" == "cp27-cp27mu" ]]; then
          sudo docker run --rm -e PLAT=manylinux2010_x86_64 -v `pwd`:/io quay.io/pypa/manylinux2010_x86_64 /io/build-wheels.sh ${{ matrix.pyversion }}
        else
          sudo docker run --rm -e PLAT=manylinux2014_x86_64 -v `pwd`:/io quay.io/pypa/manylinux2014_x86_64 /io/build-wheels.sh ${{ matrix.pyversion }}
        fi
    - name: Archive wheels
      if: matrix.pyversion != 'cp27-cp27mu'
      uses: actions/upload-artifact@v1
      with:
        name: gtsam-4.0.2-${{ matrix.pyversion }}-manylinux2014_x86_64.whl
        path: wheelhouse/gtsam-4.0.2-${{ matrix.pyversion }}-manylinux2014_x86_64.whl
    - name: Archive wheels (2.7)
      if: matrix.pyversion == 'cp27-cp27mu'
      uses: actions/upload-artifact@v1
      with:
        name: gtsam-4.0.2-${{ matrix.pyversion }}-manylinux2010_x86_64.whl
        path: wheelhouse/gtsam-4.0.2-${{ matrix.pyversion }}-manylinux2010_x86_64.whl
  mac-build:
    name: macOS Build
    runs-on: macos-latest
    strategy:
      matrix:
        pyversion: ["python"]
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Build the macOS wheels
      run: |
        ./build-macos.sh ${{ matrix.pyversion }}
    - name: Archive wheels
      uses: actions/upload-artifact@v1
      with:
        name: wheels
        path: ./wheelhouse